# Form implementation generated from reading ui file 'mainIIC.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kazakhstan))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(399, 9, 381, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MainVL = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MainVL.setContentsMargins(0, 0, 0, 0)
        self.MainVL.setObjectName("MainVL")
        self.SettingsButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.MainVL.addWidget(self.SettingsButton)
        self.TemplateHL = QtWidgets.QHBoxLayout()
        self.TemplateHL.setObjectName("TemplateHL")
        self.ChooseButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.ChooseButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ChooseButton.setObjectName("ChooseButton")
        self.TemplateHL.addWidget(self.ChooseButton)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.TemplateHL.addWidget(self.label)
        self.CreateButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.CreateButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.CreateButton.setObjectName("CreateButton")
        self.TemplateHL.addWidget(self.CreateButton)
        self.MainVL.addLayout(self.TemplateHL)
        self.StartLineHL = QtWidgets.QHBoxLayout()
        self.StartLineHL.setObjectName("StartLineHL")
        self.StartLineButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.StartLineButton.setObjectName("StartLineButton")
        self.StartLineHL.addWidget(self.StartLineButton)
        self.StartLineLineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.StartLineLineEdit.setObjectName("StartLineLineEdit")
        self.StartLineHL.addWidget(self.StartLineLineEdit)
        self.MainVL.addLayout(self.StartLineHL)
        self.StartButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.StartButton.setObjectName("StartButton")
        self.MainVL.addWidget(self.StartButton)
        self.ConsolePTE = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.ConsolePTE.setGeometry(QtCore.QRect(10, 10, 381, 491))
        self.ConsolePTE.setReadOnly(True)
        self.ConsolePTE.setPlainText("")
        self.ConsolePTE.setObjectName("ConsolePTE")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SettingsButton.setText(_translate("MainWindow", "Настройки"))
        self.ChooseButton.setText(_translate("MainWindow", "Выбрать"))
        self.label.setText(_translate("MainWindow", "/"))
        self.CreateButton.setText(_translate("MainWindow", "Создать шаблон Excel"))
        self.StartLineButton.setText(_translate("MainWindow", "Задать начальную строчку в Excel"))
        self.StartLineLineEdit.setText(_translate("MainWindow", "11"))
        self.StartButton.setText(_translate("MainWindow", "Измерять"))
